language: cpp

compiler:
        - gcc

before_install:
        - sudo apt-get update

install:
        - sudo apt-get install -y pkg-config opencv

script:
        - ls
        # Build sessie_0
        - cd sessie_0
        - cmake CMakeLists.txt
        - make
