language: cpp

compiler:
        - gcc

before_install:
        - sudo apt-get update

before_script:
       - git clone https://github.com/opencv/opencv.git
       - cd opencv
       - git checkout 3.4
       - mkdir build
       - cd build
       - cmake ..
       - make -j4
       - sudo make -j4 install
       - cd ../..

script:
        - ls
        # Build sessie_0
        - cd sessie_0
        - cmake CMakeLists.txt
        - make
        - cd ..
        # Build sessie_1
        - cd sessie_1
        - cd opdracht_1
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_2
        - cmake CMakeLists.txt
        - make
        - cd ../..
        # Build sessie_2
        - cd sessie_2
        - cmake CMakeLists.txt
        - make
        - cd ..
        # Build sessie_3
        - cd sessie_3
        - cd opdracht_1
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_2
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_extra
        - cmake CMakeLists.txt
        - make
        - cd ../..
        # Build sessie_4
        - cd sessie_4
        - cd opdracht_1
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_2
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_3
        - cmake CMakeLists.txt
        - make
        - cd ../..
        # Build sessie_5
        - cd sessie_5
        - cd opdracht_1
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_2
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_3
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_4
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_extra
        - cmake CMakeLists.txt
        - make
        - cd ../..
        # Build sessie_6
        - cd sessie_6
        - cd opdracht_1
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_2
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_3
        - cmake CMakeLists.txt
        - make
        - cd ..
        - cd opdracht_extra
        - cmake CMakeLists.txt
        - make
        cd ../..
